<?php

return [
    [
        'name' => 'appkey',
        'title' => '应用key',
        'type' => 'string',
        'content' => [],
        'value' => 'LTAI4G8d2QAmUmqSPGZQnjYJ',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'appsecret',
        'title' => '应用secret',
        'type' => 'string',
        'content' => [],
        'value' => 'LSvcnoDVLoLrIF7wx4jdRLL0nn1Qd7',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'regionid',
        'title' => '应用regionid',
        'type' => 'string',
        'content' => [],
        'value' => 'cn-hongkong',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'signname',
        'title' => '应用signname',
        'type' => 'string',
        'content' => [],
        'value' => '解忧惠',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isTemplateSender',
        'title' => '是否使用短信模板发送',
        'type' => 'radio',
        'content' => [
            '否',
            '是',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'template',
        'title' => '短信模板',
        'type' => 'array',
        'content' => [],
        'value' => [
            'register' => 'SMS_206536765',
            'editLoginPwd' => 'SMS_206536765',
            'editPayPwd' => 'SMS_206536765',
            'mobilelogin' => 'SMS_206536765',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
