<?php

return [
    [
        'name' => 'appkey',
        'title' => '应用key',
        'type' => 'string',
        'content' => [],
        'value' => 'sa',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'appsecret',
        'title' => '应用secret',
        'type' => 'string',
        'content' => [],
        'value' => 'sdf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'regionid',
        'title' => '应用regionid',
        'type' => 'string',
        'content' => [],
        'value' => 'sdf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'signname',
        'title' => '应用signname',
        'type' => 'string',
        'content' => [],
        'value' => 'asdf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isTemplateSender',
        'title' => '是否使用短信模板发送',
        'type' => 'radio',
        'content' => [
            '否',
            '是',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'template',
        'title' => '短信模板',
        'type' => 'array',
        'content' => [],
        'value' => [
            'register' => '',
            'editLoginPwd' => '',
            'editPayPwd' => '',
            'mobilelogin' => '',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
