<?php

return [
    [
        'name' => 'ini',
        'title' => '客户端配置',
        'type' => 'array',
        'value' => [
            'name' => '新零售商城',
            'logo' => '/assets/addons/wanlshop/img/common/logo.png',
            'copyright' => '2021 深圳前海万联科技有限公司',
            'urlschemes' => 'wanlshop',
            'package_name' => 'com.wanlshop.www',
            'cdnurl' => 'http://localhost',
            'appurl' => 'http://localhost/api',
            'socketurl' => 'ws://localhost:7272',
            'debug' => 'N',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '客户端参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sdk_amap',
        'title' => '高德地图SDK配置',
        'type' => 'array',
        'value' => [
            'amapkey_web' => '0a9f67a6f8f7cc3315d30846a0fde88b',
            'amapkey_ios' => 'd8b84cf540bcca9928db69b0119fc152',
            'amapkey_android' => '6c3f7522aab215e0704225adaad9f73e',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '高德地图SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sdk_qq',
        'title' => '腾讯开放SDK配置',
        'type' => 'array',
        'value' => [
            'qq_appid' => '10******36',
            'gz_appid' => 'wx6****************7a',
            'gz_secret' => 'd4a****************c6',
            'gz_token' => 'NspH****************NPpF',
            'gz_aeskey' => 'OHT********************************k0R',
            'gz_debug' => '0',
            'gz_loglevel' => 'debug',
            'gz_callback' => '/wanlshop/user/third',
			'gz_notify_url' => '/wanlshop/callback/notify/type/jssdk',
            'wx_appid' => 'wx******************88',
            'wx_appsecret' => '22***************************cc',
            'wx_universal_links' => 'https://wanlshop.com/',
            'mch_id' => '16************75',
            'key' => 'cPoF********************************ds',
            'notify_url' => '/wanlshop/callback/notify/type/wechat',
            'pay_cert' => '0',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '腾讯开放SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sdk_alipay',
        'title' => '支付宝SDK配置',
        'type' => 'array',
        'value' => [
            'app_id' => '20************21',
            'notify_url' => '/wanlshop/callback/notify/type/alipay',
            'return_url' => '/wanlshop/callback/return/type/alipay',
            'ali_public_key' => '',
            'private_key' => '',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '支付宝SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sdk_weibo',
        'title' => '微博开放SDK配置',
        'type' => 'array',
        'value' => [
            'appkey' => '35********94',
            'appsecret' => '0a********************************7f',
            'redirect_uri' => '/wanlshop/callback/weibo',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '微博开放SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'kuaidi',
        'title' => '快递100 SDK',
        'type' => 'array',
        'value' => [
            'secretKey' => 'gm********34',
            'callbackUrl' => '/wanlshop/callback/kuaidi',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '快递100 SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'h5',
        'title' => 'H5客户端',
        'type' => 'array',
        'value' => [
            'domain' => 'https://m.wanlshop.com',
            'title' => '新零售电商平台',
            'router_mode' => 'hash',
            'router_base' => './',
            'https' => 'N',
            'qqmap_key' => 'V3JBZ-C7Z36-BL7S6-M67TX-6WORS-2TBMN',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'H5客户端配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_weixin',
        'title' => '微信小程序',
        'type' => 'array',
        'value' => [
            'appid' => 'wx****************849a',
            'appsecret' => '45********************************67',
            'scope_userLocation' => '演示定位能力',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '微信小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_alipay',
        'title' => '支付宝小程序',
        'type' => 'array',
        'value' => [
            'appid' => '20**********76',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '支付宝小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_baidu',
        'title' => '百度小程序',
        'type' => 'array',
        'value' => [
            'appid' => '',
            'appsecret' => '',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '百度小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_toutiao',
        'title' => '头条小程序',
        'type' => 'array',
        'value' => [
            'appid' => '',
            'appsecret' => '',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '头条小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_qq',
        'title' => 'QQ小程序',
        'type' => 'array',
        'value' => [
            'appid' => '11*****49',
            'appsecret' => 'EV***************HX',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'QQ小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'style',
        'title' => '样式配置',
        'type' => 'array',
        'value' => [
			'category_style' => '4',
            'find_nav_color' => '#ff4632',
            'find_font_color' => 'light',
            'cart_nav_image' => '',
            'cart_nav_color' => '',
            'cart_font_color' => '',
            'groups_nav_image' => '/assets/addons/wanlshop/img/show/grueps-top-bg3x.png',
            'groups_nav_color' => '#fed295',
            'groups_font_color' => 'dark',
            'user_nav_color' => '#ffeccc',
            'user_nav_image' => '/assets/addons/wanlshop/img/user/top_bg.png',
            'user_bg_color' => '#ffeccc',
            'user_bg_image' => '/assets/addons/wanlshop/img/user/user_bg.png',
            'user_font_color' => 'dark',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'App样式配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'config',
        'title' => '动态客户端配置',
        'type' => 'array',
        'value' => [
            'store_audit' => 'Y',
            'comment_switch' => 'Y',
            'tel_phone' => '0775-12345678',
            'working_hours' => '09:00~22:00',
            'shop_document' => '',
            'shop_qun' => '',
            'user_agreement' => '153',
            'privacy_protection' => '154',
            'help_category' => '1',
            'new_category' => '2',
            'sys_category' => '4',
            'auth_reply' => '欢迎使用在线客服',
            'not_online' => '[汗] 非工作时间8:00-22:00 或客服繁忙！请稍后再试~',
            'service_initial' => '您好 [微笑] 请用一句话简短描述问题~',
            'mp_weixin_id' => 'wx***************4b',
			'versionCode' => '111'
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'App参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'order',
        'title' => '订单配置',
        'type' => 'array',
        'value' => [
            'cancel' => '3',
            'receiving' => '7',
            'comment' => '7',
            'customer' => '7',
            'autoagree' => '3',
            'returntime' => '7',
            'receivingtime' => '7',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '订单参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'find',
        'title' => '发现页配置',
        'type' => 'array',
        'value' => [
            'app_switch' => [
                'new' => 'new',
                'live' => 'live',
                'video' => 'video',
                'want' => 'want',
                'show' => 'show',
            ],
            'mp_switch' => [
                'new' => 'new',
                'live' => 'live',
                'video' => 'video',
                'want' => 'want',
                'show' => 'show',
            ],
            'h5_switch' => [
                'new' => 'new',
                'live' => 'live',
                'video' => 'video',
                'want' => 'want',
                'show' => 'show',
            ],
            'wechat_switch' => [
                'new' => 'new',
                'live' => 'live',
                'video' => 'video',
                'want' => 'want',
                'show' => 'show',
            ],
            'personalExamine_switch' => 'Y',
            'allExamine_switch' => 'Y',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '订单参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'live',
        'title' => '直播配置',
        'type' => 'array',
        'value' => [
            'liveDomain' => 'live.wanlshop.com',
            'pushDomain' => 'rtmp.wanlshop.com',
            'builderTime' => '60',
            'pushKey' => '0*****v',
            'liveKey' => 'l*****d',
            'liveCnd' => 'https://play.wanlshop.com',
            'appName' => 'wanlshop',
            'transTemplate' => 'ld',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '订单参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'video',
        'title' => '视频配置',
        'type' => 'array',
        'value' => [
            'accessKeyId' => 'LT****************Gu',
            'accessKeySecret' => 'jw****************Lrq',
            'workflowId' => '134****************da41',
            'privateKey' => 'PHl****************Tyt',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '视频参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'withdraw',
        'title' => '提现配置',
        'type' => 'array',
        'value' => [
            'state' => 'Y',
            'minmoney' => 100,
            'monthlimit' => 0,
            'servicefee' => 6,
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '商城提现参数配置',
        'ok' => '',
        'extend' => '',
    ],
	[
        'name' => 'redis',
        'title' => 'Redis配置',
        'type' => 'array',
        'value' => [
            'host' => '127.0.0.1',
            'port' => '6379',
            'password' => '',
            'select' => '0',
            'timeout' => '0',
            'persistent' => 'Y',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'Redis参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '不需要此处配置任何参数，请在 [多用户商城] - [客户端管理]和[系统管理] 中管理配置',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
